objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>cscrm__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscrm__Address_Details__c</fullName>
        <formula>IF( ISBLANK(cscrm__Street__c) , &apos;&apos;, cscrm__Street__c +&apos;,&apos;) + 
IF( ISBLANK(cscrm__State_Province__c) , &apos;&apos;, &apos; &apos; + cscrm__State_Province__c +&apos;,&apos;) + 
IF( ISBLANK(cscrm__City__c) , &apos;&apos;, &apos; &apos; + cscrm__City__c +&apos;,&apos;) + 
IF( ISBLANK(cscrm__Zip_Postal_Code__c) , &apos;&apos;, &apos; &apos; + cscrm__Zip_Postal_Code__c +&apos;,&apos;) + 
IF( ISBLANK(cscrm__Country__c) , &apos;&apos;, &apos; &apos; + cscrm__Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__State_Province__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AddressCreation.cls
/**
* This web service is used to inset/upsert data into cscrm__Address__c (Premise)
* 
* @author Petar Miletic
* @ticket SFDT-15
* @since  07/01/2016
*/
global class AddressCreation {
    /*
        Inserts/Upserts data into cscrm__Address__c. Used to store addresses from external system
    */   
    webservice static string setAddress(string accountId, string externalAddressId, string city, string houseNumber, string houseNumberExtension, string street, string postalCode) {
        system.debug('++++++entered setAddress method');
        List<cscrm__Address__c> addresses = [SELECT cscrm__Account__c,
                                                LG_AddressID__c,
                                                cscrm__Address_Details__c,
                                                cscrm__City__c,
                                                cscrm__Country__c,
                                                LG_HouseNumber__c,
                                                LG_HouseNumberExtension__c,
                                                cscrm__State_Province__c,
                                                cscrm__Street__c,
                                                cscrm__Zip_Postal_Code__c 
                                             FROM cscrm__Address__c 
                                             WHERE LG_AddressID__c = :externalAddressId and cscrm__Account__c = :accountId];

        if (addresses != null && addresses.size() > 0) {
            
            for (cscrm__Address__c a :addresses) {
                a.cscrm__Account__c = accountId;
                // a.LG_AddressID__c = externalAddressId;
                a.cscrm__City__c = city;
                //a.cscrm__Country__c = country;
                a.LG_HouseNumber__c = houseNumber;
                a.LG_HouseNumberExtension__c = houseNumberExtension;
                //a.cscrm__State_Province__c = province;
                a.cscrm__Street__c = street;
                a.cscrm__Zip_Postal_Code__c = postalCode;
            }
            
            upsert addresses;
        }
        else {
            
            cscrm__Address__c a = new cscrm__Address__c();
            
            a.cscrm__Account__c = accountId;
            a.LG_AddressID__c = externalAddressId;
            a.cscrm__City__c = city;
            //a.cscrm__Country__c = country;
            a.LG_HouseNumber__c = houseNumber;
            a.LG_HouseNumberExtension__c = houseNumberExtension;
            //a.cscrm__State_Province__c = province;
            a.cscrm__Street__c = street;
            a.cscrm__Zip_Postal_Code__c = postalCode;
            
            insert a;
        }
        Map<String, String> retMap = new Map<String, String>{'Result' => 'Excellent'};
        return JSON.serialize(retMap);
    }
}